name: leopay
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.19.0

  # Firebase
  firebase_core: 3.15.2
  firebase_auth: ^5.3.4
  cloud_firestore: 5.6.12

dev_dependencies:
  flutter_test:
    sdk: flutter # Flutter testing framework
  flutter_lints: ^5.0.0 # Recommended lint rules for better coding practices

# Flutter-specific configuration
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
